### ISSUE TITLE
pre release v2.0.0-rc1

### ISSUE THREAD

**Issue by digital-mine** [nochowderforyou/clams#317]
Is it ok to use it already?

What are the main benefits in front of the old version 1.4.17?

Thank you

**Comment by creativecuriosity** [comment]
This should be the branch that merged a ton of bitcoin core main branch code; so, there are a ton of updates/improvements.  
  
That said, it is a release candidate and shouldn't be considered stable.

**Comment by digital-mine** [comment]
better to wait than,

I was curious about more details from the dev, should be @dooglus am I right?

**Comment by falsificado** [comment]
I am using it, and apart from the initial discovery of peers, its working flawless. Using approximately the same RAM and cpu time, but the initial sync is much faster (and this is a well-known problem in clam for a lot of time). Staking and transfering funds works as expected

**Comment by digital-mine** [comment]
I'll give it a shot than!
I hoped @dooglus could say something about this pre release as he wrote it.

**Comment by dooglus** [comment]
From what I remember I never got it to sync the full chain from scratch. It got stuck at various points apparently at random. As far as I know we never found the problem, and xploited has since moved on to working on a different coin's client with a view to massaging it to become the new CLAM client.

I doubt using this v2.0.0-rc1 will lose you any coins, but can't promise anything. I expect the worst that will happen is it gets stuck at some point when syncing new blocks. But I've not spent much time running it when I found it to be less reliable than the current official release.

**Comment by digital-mine** [comment]
Thanks @dooglus 
Are you going to further develop this version in the near future?

**Comment by abmohan** [comment]
Thanks, @dooglus and @xploited for hacking away at this! If you ever need any JavaScript or Python help, please let me know

**Comment by l0rdicon** [comment]
Closing issue, unrelated to client v2.1.0
